sudo: false
language: node_js
node_js:
- stable
script:
- npm run build-all
deploy:
  tag: beta
  provider: npm
  email: iwata0303@gmail.com
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: mSfL7GyfgIaphEASmnOe/feqJ4JAG4GR662qPlDMxF/ng/9dmNE3QuMK3CrFkGyL+eCThZOdjjSLtXfos8xN/Miwbrdh5DI67un2aJptBS+uR6VrP0U6sqoY345RRVIWt1FPHJXqXRlCnoUvw6RAK5aduoZOXq/oP8kq9e8t9nMEkFcRbuH/zT3h6wojfl4ImROGIIARnf3iQTIreyU1G1xsv5+6RBkS/FgnOaZSuopQyj7hRNYwXD9hRjAFoYfiqW2vSuefhPtLkkR3O1/n4Pyt9VHfWwen03zC/Zf+oLp76orS5nWYz5kVVoRNhoBc9P5vI3aN4qs2HpbYg4Nox8rt/RRbMYTL8PouGESAL/mVN9iIXktpm73vf/M+WryIi9eS61WCWja4AG897v4uGbB2WvG4MS1T+HyLf+jsLSWfNxE2HDNaXtVllmLIkQZiYYwTlQc/cANwIvN4P8uoK6zsWjVylnZGvNDVRpyqn5ZWY0q3kb0IicQrJCoBVA+bc0eN2Ugw/8P9rt3oBrZINoct+QqJTYh07R7a/+8H4O4tczZwA0qoaEp8HQhcFFC9vRhept+Rue5XG2oRryE+d3i8W6ZAqw9W4yHvlJESO1EKZHnqNwQZtE7nC8CnKfMmQ7y7j3LOuhv4uJVFEUPuUyLJu/WnNKcrqqcmbSgzHAU=
after_deploy:
- git add dist -f
- git add example -f
- 'git commit -m "Travis CI: update gh-pages"'
- 'git push --quiet "https://${GH_TOKEN}@github.com/wonderful-panda/vue-vtable" HEAD:gh-pages --force'
env:
  global:
    secure: QEFctF2iCnY1nszuLxMnzzHlu5P2Ujfv2Zk/YnkSqpXWCxC2U+aHwz7TNdQR/7Hhr2T8+aBz/nkxmrmCPEl1i4rTFztQ8s8Uj7NV2WD5s3PhQI6iMRAGjZL+ybwhbyvVuMN6oZSbH3M/TAw3yUGFalR7Wx/9fCSNzSvIRjbXt2Ky87gSm6BAfdZerfPv7oQWNUER+rDqBa6/GOMtzOm2OCkR7zlmqfAdNei9cS94ZMVRxw5ZDgVNwdBNqywDrSdbLrIAwr3NDBkrl232VIWbmSy2Eni4Fc53daNXhOZ6zZqf2mxNMzV2Xkg6sGMmACoqx92KyN2veRPOI4McBi1Vmp8aD8zYmzKbYLYSKWG/y35fDZVDlX5a3jahXt7kEfZIjgCzkmNEo5WqxMhOMbawYTDh5gJLUlC2pRpKCllycFYSTiuynOGR/yzS4+m61x4hzf9nTUbyMAXmOvzToTkQv+Pq1HcjDuTFiI84VY5XIK6cjEnXzAVElID+35vIfgPar3u3Hbme82x6Pi088AQ/afCnCogM8nNWgtmc8pt4J6few/jU63/WEmwybuWH9fRJu3qc1QVgs/1Dt9+PgnI9b9/BeXBzytc3V3k5MtK0cmXg0oNG5UFVfjn1oivPFTBMjuhx1zi4t0ugZGE3WSGrjl41Lv4z7hrkAybjCDF6cFg=
