sudo: false
language: node_js
node_js:
- stable
script:
- npm run build-all
deploy:
  provider: npm
  email: iwata0303@gmail.com
  tag: beta
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: mSfL7GyfgIaphEASmnOe/feqJ4JAG4GR662qPlDMxF/ng/9dmNE3QuMK3CrFkGyL+eCThZOdjjSLtXfos8xN/Miwbrdh5DI67un2aJptBS+uR6VrP0U6sqoY345RRVIWt1FPHJXqXRlCnoUvw6RAK5aduoZOXq/oP8kq9e8t9nMEkFcRbuH/zT3h6wojfl4ImROGIIARnf3iQTIreyU1G1xsv5+6RBkS/FgnOaZSuopQyj7hRNYwXD9hRjAFoYfiqW2vSuefhPtLkkR3O1/n4Pyt9VHfWwen03zC/Zf+oLp76orS5nWYz5kVVoRNhoBc9P5vI3aN4qs2HpbYg4Nox8rt/RRbMYTL8PouGESAL/mVN9iIXktpm73vf/M+WryIi9eS61WCWja4AG897v4uGbB2WvG4MS1T+HyLf+jsLSWfNxE2HDNaXtVllmLIkQZiYYwTlQc/cANwIvN4P8uoK6zsWjVylnZGvNDVRpyqn5ZWY0q3kb0IicQrJCoBVA+bc0eN2Ugw/8P9rt3oBrZINoct+QqJTYh07R7a/+8H4O4tczZwA0qoaEp8HQhcFFC9vRhept+Rue5XG2oRryE+d3i8W6ZAqw9W4yHvlJESO1EKZHnqNwQZtE7nC8CnKfMmQ7y7j3LOuhv4uJVFEUPuUyLJu/WnNKcrqqcmbSgzHAU=
after_deploy:
- git add dist -f
- git add example -f
- 'git commit -m "Travis CI: update gh-pages"'
- git push --quiet "https://${GH_TOKEN}@github.com/wonderful-panda/vue-vtable" HEAD:gh-pages
  --force
env:
  global:
    secure: kM4Wn5r78fYygy5D6gVzamVQoGkbj9AUsklipXVsHV0pmkTkFr9fJpYDsYk+ZP3I1XZOv5qGlLCbz1yiZVC0pSs8av0fViFoscwP3xhtF81PCdGw3294d04cqyAk/hp5xHm7cmxdanx3V7RxOlfQwN1uh/5oX3wPfWj/ORB72OCg4mf86YVzdWUZPV4XdLBY31WVbHMMDDJzBRjtbJSJnxWTmh6MYaUtKNrShgHahDA3Rweeb7amcofGrAcCtnHUBM9VqVykm6vpsJsrOX3J+UdmOU3fsYXaLVKYA7Vug5HGh7wxa5v5d/nX2KR+kWnmmPDjMfn23lkXZ70r4QHCydI5+a+OKXwDR1bQHWcrxIEv5nnDCIVxp1CbvRJNh9XIMq/xTacCFuZgbR4XoKJWfyX6g7WC7/bLvfb+opp7AgZG43C/4SF7lOHv0ugliUF8OjleK+Ic1PNoAvkEe5KyrNmD542WX0A0+cdVE00//IDk6t8eiiLQ8vEd4Mk8hX+1k/6jA1zUUnzcTmWoas74Znu+oKILL2w69H6kHTkSTKdLkYKp/gNZf68K5kiS18yte5ETFNRY31uSbopQsOSThnCVuA6cdRAyJuGC9Ms4xaPMm4GJgMeEeKqcUFY5oJd/AwRyN+mrMvy3V0XqeC5QwXKATbZtT8C5SEc3PyPQkbQ=
